= Journal AoC 2023
:sourcepath: src/test/java

== https://adventofcode.com/2024/day/1[Day 1]

There was nothing special about this exercise.
Didn't optimize the computation for the second part, as the input was not that big.

== https://adventofcode.com/2024/day/2[Day 2]

For the distance comparison, I use a little function with a reduce.
As I need to drag the error to the end, I use `Integer.MAX_VALUE` to be sure, that the distance is the highest possible.

[source, java, indent=0]
----
private boolean distantCheck(List<Integer> list) {
    return list.stream().reduce((n, m) -> (Math.abs(n-m) <= 3 && Math.abs(n-m) > 0)? m : Integer.MAX_VALUE).filter(n -> n == Integer.MAX_VALUE).isEmpty();
  }
----

To check, if it is always ascending or descending, an equals check to a sorted and sorted-reversed input list is done.

For part 2 I used an `IntStream.range()` to get all possible indices, which have to be removed and used the manipulated list on the same checks as in part 1.


== https://adventofcode.com/2024/day/3[Day 3]

Using some regex, this is quite simple.
For getting the needed substrings I used `(mul\\(\\d+,\\d+\\))` for the first part and `(mul\\(\\d+,\\d+\\))|(do\\(\\))|(don't\\(\\))` for the second one.
It was necessary to know, that the input should be treated as one line, but the file itself had multiple ones.
With this in mind, you can just `flatMap` the internal `List` s and get one `List` with the elements to process.

[source, java, indent=0]
----
Files.readAllLines(fileName).stream().map(string -> extractCorrectInstructions(string, pattern)).flatMap(Collection::stream).mapToLong(s -> processItem(s, compute)).sum()
----

For part 2, I just switch on and off the processing with an `AtomicBoolean`:

[source, java, indent=0]
----
private long processItem(String s, AtomicBoolean compute) {
    return switch (s) {
      case "don't()" -> {
        compute.set(false);
        yield 0;
      }
      case "do()" -> {
        compute.set(true);
        yield 0;
      }
      default -> multiplyIfNeeded(compute.get(), s);
    };
}
----


== https://adventofcode.com/2024/day/3[Day 3]

The first, more complex one. I didn't find an easy solution for part one yet.
Just stupid "go in any direction" was the solution, with 8 nearly similar methods for each direction.

* [ ] need to optimize this. (https://github.com/ronnypolley/adventofcode/issues/65[#65])

Part 2 was actually way easier.

[source, java, indent=0]
----
private String xmas(String[][] array, int i, int i1, int i2, int j, int j1, int j2) {
    if (i < 0 || j < 0 || i2 <0 || i >= array.length || i2 >= array.length || j2 >= array[i].length) {
      return "";
    }
    return array[i][j].concat(array[i1][j1]).concat(array[i2][j2]);
}
----

Actually, this can als be simplified by an `Array`/`List` of indices.


[source, java, indent=0]
----
private String xmas(String[][] array, int[] is, int[] js) {
    if (i[0] < 0 || j[0] < 0 || i[2] < 0 || i[0] >= array.length || i[2] >= array.length || j[2] >= array[i[0]].length) {
      return "";
    }
    return array[i[0]][j[j]].concat(array[i[1]][j[1]]).concat(array[i[2]][j[2]]);
}
----

Not sure, if I would you this in an actual project, as the readability lacks a lot, but it's okay for tihs here.

This is called from:

[source, java, indent=0]
----
private long findXmas2(String[][] array, int i, int j) {
  if (Stream.of(xmas(array, new int[]{i-1, i, i+1}, new int[]{j-1, j, j+1}),
       xmas(array, new int[]{i+1, i, i-1}, new int[]{j-1, j, j+1})).filter(string -> "MAS".equals(string) || "SAM".equals(string)).count() == 2) {
    return 1;
  }

  return 0;
}
----

Only if I have "MAS" or "SAM" in both of the strings, I will mark it as found.
