= Journal AoC 2023
:sourcepath: src/test/java

== https://adventofcode.com/2023/day/1[Day 1] 

The _"oneight"_ was a nice trap. I fixed this with a little hack replacing the string with first letter + number + last letter.

.Replacement code from Day01Test.java
[source, java, indent=0]
//include::{sourcepath}/com/adventofcode/day01/Day01Test.java[tags=replace]
----
return combineDigits(Files.lines(file).map(line -> line.replace("one", "o1e"))
				.map(line -> line.replace("two", "t2o")).map(line -> line.replace("three", "t3e"))
				.map(line -> line.replace("four", "f4r")).map(line -> line.replace("five", "f5e"))
				.map(line -> line.replace("six", "s6x")).map(line -> line.replace("seven", "s7n"))
				.map(line -> line.replace("eight", "e8t")).map(line -> line.replace("nine", "n9e")));
----

== https://adventofcode.com/2023/day/2[Day 2]

This one was really straight forward. Nothing special here.
Added a class for creating the game from the input including and two method for doing the main work, 
which were called from streams.

.Part 1 - finding not possible rounds
[source, java, indent=0]
//include::{sourcepath}/com/adventofcode/day02/Game.java[tags=part1,indent=0]
----
boolean isPossible(int maxRed, int maxBlue, int maxGreen) {
		return !rounds.stream().filter(round -> round.blue > maxBlue || round.red > maxRed || round.green > maxGreen)
				.findFirst().isPresent();
	}
----

.Part 2 - finding minial values per round
[source, java, indent=0]
//include::{sourcepath}/com/adventofcode/day02/Game.java[tags=part2,indent=0]
----
static CubesRevealed mapToMinimalSet(CubesRevealed input1, CubesRevealed input2) {
			var cubesRevealed = new CubesRevealed();
			cubesRevealed.red = input1.red > input2.red ? input1.red : input2.red;
			cubesRevealed.green = input1.green > input2.green ? input1.green : input2.green;
			cubesRevealed.blue = input1.blue > input2.blue ? input1.blue : input2.blue;
			return cubesRevealed;
		}
----
 
== https://adventofcode.com/2023/day/3[Day 3]

Well, mainly working as a product owner, I lack some of the newer features in the programming languages.
But this is the nice thing on AoC, I can learn :D. 
I wrote my first ever `FunctionalInterface`:

[source,java]
----
@FunctionalInterface
public interface CheckDigitsAround<T, U, V, R> {
	// this interfaces is used for the check*Around methods to be referenced.
	R apply(T j, T i, V listOfStrings);
}
----

This I used to have the two methods for finding digits around the symbols.
As I implemented the first part directly by finding symbols and backtrack around them, the second part was trivial. 

== https://adventofcode.com/2023/day/4[Day 4]

I could use the bitshifting power! The last time I used this, was at the university.
For the second part, I didn't read the question well, so I used the same computation as in part 1.
That we only have to find the amount of cards took me some time.
The first version was a slow recursion variant, that worked. (https://github.com/ronnypolley/adventofcode/blob/aa1433e28557081f34439b2e9f3266b1106711c4/adventofcode-2023/src/test/java/com/adventofcode/day04/Day04Test.java[recursive solution])
Than I made an iterative one, which was much faster.

.Iternative solution
[source,java]
----
mapCards(file).forEach(g -> {
	if (!g.retaining().isEmpty()) {
		// If we have matching numbers, we look into the already created list and add to
		// each possible card the amount the current card was found.
		list.subList(g.id + 1, g.id + 1 + g.retaining().size()).forEach(l -> l.amount += list.get(g.id).amount);
	}
});
----

== https://adventofcode.com/2023/day/5[Day 5]

I think I overengineered this a little bit with the Enum and the Maps.
My first attempt had me map this all serpartly, what is not neccessary.
So I could reduce the complexity a little bit by concatinating the mappings.

For part 2 my first stupi attempt used too much memory and Java quitted. 
I tried to map everything into lists, which were too big here. 
The second attempt (just burte force computing) took a lot of time. 

* [ ] make part 2 faster

== https://adventofcode.com/2023/day/6[Day 6]

This was really easy one. Just some computing and merging. Easyly be done by using streams.
It would also be an easy one to write in Haskell, 
what I already planned this year, but because of the time (with kids and family and quarterly planning)  not did.
Used a `record` for the Race class representing the input values.

* [ ] I had the idea of loading the input data through the code, but not sure if the effort is worth it.


== https://adventofcode.com/2023/day/7[Day 7]

Nice one, which was not as complicated as I first thought.
I had a little typo in the solution for part1 that's why it took longer, than it should:
I mapped the letters to other codepoints, so that they are ordered correctly. Here I mapped the same number to J and T.
This worked for the test input, but not for the actual one.

I have a nice little _set_ related method for determining the type.
For the things, that are not unique I use a method to compute the amount of the card, which is the most used in the hand.

[source, java]
----
int getType() {
	// Five of a kind
	var count = hand.chars().distinct().count();
	if (count == 1) {
		return 7;
	}
	if (count == 2) {
		// 6 for Four of a kind and 5 for full house
		return countMostCommonCard(hand.chars()).getValue() == 4 ? 6 : 5;
	}
	if (count == 3) {
		// 3 for three of a kind and 2 for two pairs
		return countMostCommonCard(hand.chars()).getValue() == 3 ? 4 : 3;
	}
	// High card
	if (count == 4) {
		return 2;
	}
	return 1;
}
----

In the `countMostCommonCard` method I first used the `HashMap#merge` method, which worked not as I expected.


For the second part, I used the brute force approch to find the highest hand with the Jokers.
As the input was not so big, this worked really good and the code for some more efficent search would be much larger, than the one I have now.

And the Joker just got a smaller number reprenstation now.

[source,java]
----
@Override
protected IntUnaryOperator mapCardsToInts() {
	return i -> switch (i) {
	case 74 -> 10;
	default -> super.mapCardsToInts().applyAsInt(i);
	};
}
----

== https://adventofcode.com/2023/day/8[Day 8]

Again a brute force attempt... I had the actual solution in mind, while writing the code.
To use the least common mulitplier sounded right, but I could not logically apply it the the complete list of instructions.
The main thing is, that no own says that you will always go the same nodes when you reached an end node.
That's why it is not obvious to use the LCM algorithm, but it worked.

First I used a brute-force way, but taking up more than 10 minutes, it was clear, that this can not be right, so I tried the LCM than and it gave the correct answer.

The issue with the LCM is, that one assumption is missing in the description:

NOTE: That the length of all ways from `A->Z->Z...->Z` are from the same length for each starting point `A`. 
This is essential for this approach. Else there might be ways that change in length and so, we can not just compute the first length and use it as the input for the LCM.


== https://adventofcode.com/2023/day/15[Day 15]

This was an easy one again. Just took me some time, as I didn't read the "manual" completely :smirk:.

There is nothing special to this and it's relative small amount of code.
The first part can be written as a one liner. Just splitted the input parsing from the computation.
The hash function is also straight forward for any functional driven language.

[source, java]
----
private static int hashAlgorithm(String value) {
	return value.codePoints().reduce(0, (left, right) -> ((left + right) * 17) % 256);
}
----

Part 2 has a little more to it, but the main functionality is encapsulated in the following code:

[source, java]
----
strings.forEach(l -> {
	int hash = hashAlgorithm(l.name);
	hashmap.computeIfAbsent(hash, k -> new LinkedList<>());
	if (l.shouldRemove()) {
		hashmap.get(hash).remove(l);
	} else if (hashmap.get(hash).contains(l)) {
		hashmap.get(hash).set(hashmap.get(hash).indexOf(l), l);
	} else {
		hashmap.get(hash).add(l);
	}
});
----

Here the three cases of the task can be seen (the deletion, the change and the adding).
As I used `record` classes for this, I had to exchange the whole object instead of just changing the focal length.
I also implemented the hash functionality on this record, so that I can use it for the `contains` and `indexOf` functions. In the default implementation, the focal length is used for the `hashCode`. 
But the lenses should be the same, if their names are the same.

